import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'

// These styles apply to every route in the application
import './layout.css'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'

import SideBar from '../components/SideBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body>
        <ToastContainer />
        <SideBar />
        <div className="flex px-10 pt-10 flex-1 items-center justify-center overflow-y-auto">
          {children}
        </div>
      </body>
    </html>
  )
}
