import type { Metadata } from 'next'

// These styles apply to every route in the application
import './layout.css'
import './globals.css'

import SideBar from '../components/SideBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-screen">
        <SideBar />
        {children}
      </body>
    </html>
  )
}
